FROM node:18-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --quite
COPY . .
RUN npm run build task

FROM node:18-alpine as production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --quite --only=production
COPY . .
COPY --from=build /usr/src/app/dist ./dist
CMD ["node", "dist/apps/task/main"]
